### ISSUE TITLE
Question about auto shuffling

### ISSUE THREAD

**Issue by Eneswar** [chitwan27/lineArrange#1]
Hey, I have a question about this plugin and another one, I use a plugin called spaced repetition, which is basically flashcards.
And sometimes my questions have a list of options.

Example:
![image](https://github.com/chitwan27/lineArrange/assets/22943781/99620daf-73c3-49ad-b62b-2a3734d8cc08)

Would it be possible when a flashcard comes up that has a list like this, it shuffles the list automatically?

**Comment by chitwan27** [comment]
Hi @Eneswar ,

Thanks for reaching out!

I understand your request about shuffling the options in your flashcards automatically. However, my plugin is designed to shuffle or sort lines **manually** through a command and cannot automatically detect or trigger actions based on other plugins like the flashcard plugin.

I think the best solution would be integrating an option shuffling feature directly into the spaced repetition plugin. This way, the options could be randomized automatically whenever a flashcard is generated. 

Best,
Chitwan
